
[formatter.vale]
command = "vale"        # formatter command
options = []            # cli options
includes = [ "*.qmd" ]  # globs to include
excludes = []           # globs to exclude
priority = 0            # if multiple formatters
